[package]
name = "wgpu_fft"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "*"
bytemuck = { version = "*", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
num = "*"